name: listing files
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: ls output
          run: |
             ls 
        - name: checkout the code
          uses: actions/checkout@v3
              
        
      
