name: listing files
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: check my repository details
          run: echo "${{ github.repository }}"
        - name: checkout the code
          uses: actions/checkout@v3
        - name: ls output
          run: |
             ls       
        
      
